### PR TITLE
Better knora.org web site

### LINKED ISSUE #5: Make a better knora.org web site
This issue replaces the issue [#888](https://github.com/dhlab-basel/knora/issues/888) from the knora repository.
@benjamingeer suggested to make a better knora.org web site:

> It should:
> * Clearly say what Knora is
> * Briefly describe Knora's main features (one sentence each), in not-too-technical language, with links to somewhat longer explanations (one paragraph each)
> * Provide links to:
>   * "Quick start", "Try Knora", "Install Knora", or some such thing
>   * Code on GitHub
>   * Documentation
>   * News (e.g. new releases)
>
> It should not:
> * Have an outdated academic conference video on the front page

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves [knora issue #888](https://github.com/dhlab-basel/knora/issues/888)
resolves #5

### CODE REVIEW

**Comment by kilchenmann** [comment]
when should we go online with the new page?

**Comment by benjamingeer** [comment]
Can we see what it looks like?

**Comment by kilchenmann** [comment]
You didn't run it on your machine?
Oh wait.. I have to change the images first. And we have to change or rearrange two texts.
 I will upload a screenshot here...

**Comment by benjamingeer** [comment]
How do I run it on my machine?

**Comment by kilchenmann** [comment]
It's in the README 😉

**Comment by benjamingeer** [comment]
Great, let me know when I should try it.

**Comment by kilchenmann** [comment]
I just updated the page. But I'm not sure with the pictures right now.

**Pull request merged**
